In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("Student-Performance.csv")

In [24]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [25]:
df.tail()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [26]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [27]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [28]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [29]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [30]:
le=LabelEncoder()
df["Extracurricular Activities"]=le.fit_transform(df["Extracurricular Activities"])

In [31]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [32]:
x=df.drop(columns="Performance Index")

In [33]:
y=df['Performance Index']

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=.2)

In [36]:
X_train

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6054,3,42,1,5,0
6165,4,94,0,5,9
8218,2,43,1,8,1
872,8,96,0,4,3
1513,8,99,0,8,1
...,...,...,...,...,...
7037,3,95,1,9,9
1517,4,42,1,7,0
270,4,63,1,5,3
3828,6,58,1,7,0
4608,9,51,1,4,7

In [37]:
X_test

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
8089,3,68,0,5,5
9493,7,90,1,7,2
4417,5,55,1,7,4
3447,4,49,0,4,8
3263,5,99,1,6,0
...,...,...,...,...,...
1485,6,76,1,5,7
2450,5,88,0,5,6
6333,3,54,0,8,8
9390,4,87,0,8,4
945,5,78,1,5,5

In [38]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [39]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [40]:
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [41]:
y_pred=model.predict(X_test_scaled)

In [42]:
X_test_scaled

array([[-0.72298723, -0.09491652, -0.99203175, -0.88838305,  0.14290118],
       [ 0.82475102,  1.17409804,  1.00803226,  0.29652265, -0.89890569],
       [ 0.05088189, -0.84478876,  1.00803226,  0.29652265, -0.20436778],
       ...,
       [-0.72298723, -0.90247124, -0.99203175,  0.8889755 ,  1.18470804],
       [-0.33605267,  1.0010506 , -0.99203175,  0.8889755 , -0.20436778],
       [ 0.05088189,  0.48190828,  1.00803226, -0.88838305,  0.14290118]],
      shape=(2000, 5))

In [43]:
model.predict([[ 0.75139639, -0.54365905, -0.98807114,  0.28322445,  1.20879833]])

array([51.81900234])

In [44]:
mean_squared_error(y_test,y_pred)

4.046199862761807

In [45]:
r2_score(y_test,y_pred)

0.9892807049358535

In [46]:
import pickle
with open("student_lr_final_model.pkl",'wb') as file :
    pickle.dump((model,scaler,le),file)